# Generated by Django 5.1 on 2025-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_handle', models.CharField(max_length=100)),
                ('facebook_name', models.CharField(max_length=100)),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('workshop_address_line1', models.CharField(max_length=200)),
                ('workshop_address_line2', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address_line1', models.CharField(max_length=200)),
                ('company_address_line2', models.CharField(max_length=200)),
                ('company_kvk', models.CharField(max_length=50, verbose_name='KVK Number')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('payment_url', models.URLField(blank=True)),
                ('qr_code_image', models.CharField(help_text='Filename of QR code image in static/media/', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package Price',
                'verbose_name_plural': 'Package Prices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('learn', 'Learn'), ('book', 'Book')], max_length=50)),
                ('section_key', models.CharField(help_text='Unique identifier for this content section', max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Main content text')),
                ('order', models.IntegerField(default=0, help_text='Display order on the page')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
