# Generated by Django 5.1 on 2025-11-09 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageprice',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Main content text'),
        ),
    ]
