# Generated by Django 5.1 on 2025-11-09 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_packageprice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageprice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packageprice',
            name='details',
        ),
        migrations.AddField(
            model_name='packageprice',
            name='content',
            field=ckeditor.fields.RichTextField(default='', help_text='Package details and pricing information'),
        ),
    ]
